### ISSUE TITLE
Successful Attestation on OP Mainnet Links to Goerli Etherscan

### ISSUE THREAD

**Issue by MSilb7** [sbvegan/attestation-station-interface#12]
1. Make attestation and submit transaction
2. Success pops up with a link to see the transaction
3. Link takes me to the transaction hash on OP Goerli (where the transaction doesn't exist) vs OP Mainnet Etherscan

![image](https://user-images.githubusercontent.com/4006780/207887129-83861fe5-e47e-45f5-a59c-3931019431b9.png)

**Comment by sbvegan** [comment]
Thank you for catching that, it has been updated to dynamically update the etherscan link depending on the active network.
