### ISSUE TITLE
WalletConnect QRs do not work

### ISSUE THREAD

**Issue by clacladev** [sbvegan/attestation-station-interface#20]
Hello Optimists!
I tried to connect my wallet scanning the QR codes on my Rainbow and Metamask mobile apps. But they do not work. 
The QRs get scanned properly, but then Rainbow throws an "error initialising wallet connect". While Metamask after scanning the QR, it asks to confirmation to open a link and then nothing happens.

If I connect Metamask Chrome extension, it works as expected instead.

I tried to show the QR codes both from Safari and Chrome on macOS, with the same result.
In the console of the web app I don't see any errors, so I am not sure what is happening.

Let me know if you need more info.

**Comment by sbvegan** [comment]
Thank you for reporting this, I'll make sure to look into it when I have some more bandwidth!

**Comment by clacladev** [comment]
When it’s solved I can test it
